title: Alexey's Techblog
description: Blog about Azure, Azure AD, DevOps and Security around all of it 

url: http://blog.astashin.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: Astashin
  email: astashin@outlook.com
  linkedin: alexey-a-b5591832

google_analytics: "G-MTZDJQ4EZC"

disqus:
    shortname: jagstang
